volumes:
  pg_data: 
  static_value: 
  media_value:
  migrations_works:

services:

  db: 
    image: postgres:13.0-alpine 
    env_file: .env 
    volumes: 
      - pg_data:/var/lib/postgresql/data

  woodwork: 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always 
    env_file: .env 
    depends_on: 
      - db 
    volumes: 
      - static_value:/app/static/
      - media_value:/app/media/
      - migrations_works:/app/works/migrations

  nginx:
    image: nginx:1.23.3-alpine-slim
    ports:
      - "80:80"
    env_file: .env
    depends_on: 
      - woodwork
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/ 
      - media_value:/var/html/media/
